### ISSUE TITLE
Pagedown template

### ISSUE THREAD

**Issue by tvroylandt** [rfortherestofus/tfff#1]
Make a light pagedown template to support the Oregon Voices report project

**Comment by dgkeyes** [comment]
We'll want to do this, but let's hold off until we work with the graphic designer to get a template.

**Comment by tvroylandt** [comment]
Ok

**Comment by tvroylandt** [comment]
Any update on the template ?

**Comment by dgkeyes** [comment]
I have a meeting this week. I'll let you know after that.
