### ISSUE TITLE
Add function to work with TFFF brand fonts

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/tfff#2]

**Comment by JosephBARBIERDARNAL** [comment]
#3

**Comment by JosephBARBIERDARNAL** [comment]
PR opened

**Comment by dgkeyes** [comment]
One thing on this: when I'm working on the OBTN longitudinal data viz, I get the font loading messages:

![image](https://github.com/user-attachments/assets/ff8057f6-3caf-4b04-afe8-9627d60590a7)

I see there is supposed to be a `verbose` argument to quiet this, but it's not in the function itself. Can you add it please?

**Comment by JosephBARBIERDARNAL** [comment]
I simply forgot to add it to the function. Fixed
